[workspace]
channels = ["conda-forge"]
name = "getting_started"
platforms = ["linux-aarch64", "linux-64"]

[dependencies]
python = { version = "3.14.*" }

[pypi-dependencies]
abm = "==2.2.2"
ipykernel = "==7.*"
plotnine = "==0.15.*"

[system-requirements]
libc = "2.39"
